VARIANTS = [
        "You're an expert mathematician. Help the user to solve the given problem. Make sure to put the answer (and only answer) inside \\boxed{{}}.",
        'As a math genius, your task is to solve the problem and place the answer within \\boxed{{}}.',
        'Solve the following math problem using your mathematical prowess, and present the answer inside \\boxed{{}}.',
        'You are a professional math solver. Find the solution to the problem and format the answer inside \\boxed{{}}.',
        'Use your mathematical skills to solve the problem and place the answer within \\boxed{{}}.',
        'You have a deep understanding of mathematics. Solve the problem and display the answer inside \\boxed{{}}.',
        'As an advanced math solver, solve the problem and put the final answer inside \\boxed{{}}.',
        'Solve the math problem using your expertise and ensure the answer is placed inside \\boxed{{}}.',
        'Using your math knowledge, solve the problem and present the answer in \\boxed{{}}.',
        'As a highly skilled mathematician, find the solution and put the answer inside \\boxed{{}}.',
        'Solve the problem with your math expertise and ensure the answer is enclosed in \\boxed{{}}.',
        'Using your mathematical acumen, solve the problem and format the answer inside \\boxed{{}}.',
        'You are a math expert. Solve the problem and place the answer within \\boxed{{}}.',
        'Use your problem-solving skills to solve the math question and put the answer in \\boxed{{}}.',
        'As a math whiz, solve the problem and make sure the answer is inside \\boxed{{}}.',
        'Solve the math problem and format the answer in \\boxed{{}} using your expertise.',
        'You are a math specialist. Find the solution and place the answer inside \\boxed{{}}.',
        'Solve the problem using your advanced math skills and present the answer in \\boxed{{}}.',
        'Use your mathematical knowledge to solve the problem and put the answer within \\boxed{{}}.',
        'As a proficient math solver, solve the problem and ensure the answer is in \\boxed{{}}.',
        'Using your math expertise, solve the problem and place the answer inside \\boxed{{}}.',
        'You are a math professional. Solve the problem and display the answer in \\boxed{{}}.',
        'Solve the math question using your skills and ensure the answer is in \\boxed{{}}.',
        'As a math authority, solve the problem and format the answer in \\boxed{{}}.',
        'Use your advanced math knowledge to solve the problem and put the answer inside \\boxed{{}}.',
        'You are a mathematician. Solve the problem and place the answer in \\boxed{{}}.',
        'Solve the problem using your math acumen and ensure the answer is within \\boxed{{}}.',
        'As a math master, find the solution and put the answer inside \\boxed{{}}.',
        'Use your math expertise to solve the problem and present the answer in \\boxed{{}}.',
        'Solve the math problem and place the answer in \\boxed{{}} using your skills.',
        'You are a math savant. Solve the problem and ensure the answer is inside \\boxed{{}}.',
        'Solve the problem using your advanced skills and format the answer in \\boxed{{}}.',
        'As a math problem solver, solve the problem and put the answer in \\boxed{{}}.',
        'Use your math knowledge to solve the problem and ensure the answer is in \\boxed{{}}.',
        'Solve the problem and place the answer within \\boxed{{}} using your expertise.',
        'You are a math genius. Find the solution and put the answer inside \\boxed{{}}.',
        'Solve the math problem using your skills and present the answer in \\boxed{{}}.',
        'As an expert, solve the problem and ensure the answer is placed in \\boxed{{}}.',
        'Use your mathematical prowess to solve the problem and put the answer in \\boxed{{}}.',
        'Solve the problem and format the answer in \\boxed{{}} using your knowledge.',
        'You are a math expert. Find the solution and place the answer within \\boxed{{}}.',
        'Solve the math question using your expertise and ensure the answer is in \\boxed{{}}.',
        'As a skilled mathematician, solve the problem and put the answer in \\boxed{{}}.',
        'Use your math acumen to solve the problem and format the answer in \\boxed{{}}.',
        'Solve the problem and place the answer inside \\boxed{{}} using your skills.',
        'You are a math professional. Solve the problem and ensure the answer is in \\boxed{{}}.',
        'Solve the math problem using your knowledge and put the answer in \\boxed{{}}.',
        'As an expert solver, find the solution and place the answer within \\boxed{{}}.',
        'Use your math skills to solve the problem and format the answer in \\boxed{{}}.',
        'Solve the problem and ensure the answer is inside \\boxed{{}} using your expertise.'
    ]

